# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_coeff.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(591, 426)
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 80, 441, 91))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 1)
        self.input_Kp = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Kp.setObjectName("input_Kp")
        self.gridLayout.addWidget(self.input_Kp, 1, 0, 1, 1)
        self.input_Ki = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Ki.setObjectName("input_Ki")
        self.gridLayout.addWidget(self.input_Ki, 1, 1, 1, 1)
        self.input_Kd = QtWidgets.QLineEdit(self.layoutWidget)
        self.input_Kd.setObjectName("input_Kd")
        self.gridLayout.addWidget(self.input_Kd, 1, 2, 1, 1)
        self.button_coeff_send = QtWidgets.QPushButton(self.layoutWidget)
        self.button_coeff_send.setObjectName("button_coeff_send")
        self.gridLayout.addWidget(self.button_coeff_send, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(200, 30, 142, 34))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(190, 220, 142, 34))
        self.label_5.setObjectName("label_5")
        self.layoutWidget_2 = QtWidgets.QWidget(Form)
        self.layoutWidget_2.setGeometry(QtCore.QRect(30, 260, 441, 91))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 2, 1, 1)
        self.input_Kp_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_Kp_2.setObjectName("input_Kp_2")
        self.gridLayout_2.addWidget(self.input_Kp_2, 1, 0, 1, 1)
        self.input_Ki_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_Ki_2.setObjectName("input_Ki_2")
        self.gridLayout_2.addWidget(self.input_Ki_2, 1, 1, 1, 1)
        self.input_Kd_2 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.input_Kd_2.setObjectName("input_Kd_2")
        self.gridLayout_2.addWidget(self.input_Kd_2, 1, 2, 1, 1)
        self.button_coeff_send_2 = QtWidgets.QPushButton(self.layoutWidget_2)
        self.button_coeff_send_2.setObjectName("button_coeff_send_2")
        self.gridLayout_2.addWidget(self.button_coeff_send_2, 2, 1, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Kp"))
        self.label_2.setText(_translate("Form", "Ki"))
        self.label_3.setText(_translate("Form", "Kd"))
        self.button_coeff_send.setText(_translate("Form", "Change coeff"))
        self.label_4.setText(_translate("Form", "Current Control"))
        self.label_5.setText(_translate("Form", "Torque "))
        self.label_6.setText(_translate("Form", "Kp"))
        self.label_7.setText(_translate("Form", "Ki"))
        self.label_8.setText(_translate("Form", "Kd"))
        self.button_coeff_send_2.setText(_translate("Form", "Change coeff"))
