# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'creep_test_gui.ui'
##
## Created by: Qt User Interface Compiler version 6.11.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QComboBox, QFrame,
    QGridLayout, QLCDNumber, QLabel, QLineEdit,
    QMainWindow, QMenu, QMenuBar, QPushButton,
    QSizePolicy, QSplitter, QStatusBar, QVBoxLayout,
    QWidget)

from pyqtgraph import GraphicsLayoutWidget

class Ui_CreepTestGUI(object):
    def setupUi(self, CreepTestGUI):
        if not CreepTestGUI.objectName():
            CreepTestGUI.setObjectName(u"CreepTestGUI")
        CreepTestGUI.resize(1337, 953)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Maximum, QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(CreepTestGUI.sizePolicy().hasHeightForWidth())
        CreepTestGUI.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(9)
        font.setBold(True)
        CreepTestGUI.setFont(font)
        CreepTestGUI.setMouseTracking(False)
        CreepTestGUI.setLayoutDirection(Qt.LeftToRight)
        CreepTestGUI.setAutoFillBackground(False)
        CreepTestGUI.setInputMethodHints(Qt.ImhNone)
        self.actionHardware_reset = QAction(CreepTestGUI)
        self.actionHardware_reset.setObjectName(u"actionHardware_reset")
        font1 = QFont()
        font1.setBold(False)
        font1.setKerning(False)
        self.actionHardware_reset.setFont(font1)
        self.actionSoftware_restart = QAction(CreepTestGUI)
        self.actionSoftware_restart.setObjectName(u"actionSoftware_restart")
        self.centralwidget = QWidget(CreepTestGUI)
        self.centralwidget.setObjectName(u"centralwidget")
        self.gridLayout_8 = QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName(u"gridLayout_8")
        self.splitter_13 = QSplitter(self.centralwidget)
        self.splitter_13.setObjectName(u"splitter_13")
        self.splitter_13.setOrientation(Qt.Vertical)
        self.layoutWidget = QWidget(self.splitter_13)
        self.layoutWidget.setObjectName(u"layoutWidget")
        self.gridLayout_6 = QGridLayout(self.layoutWidget)
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.splitter_6 = QSplitter(self.layoutWidget)
        self.splitter_6.setObjectName(u"splitter_6")
        self.splitter_6.setOrientation(Qt.Vertical)
        self.splitter_7 = QSplitter(self.splitter_6)
        self.splitter_7.setObjectName(u"splitter_7")
        self.splitter_7.setOrientation(Qt.Vertical)
        self.splitter_8 = QSplitter(self.splitter_7)
        self.splitter_8.setObjectName(u"splitter_8")
        self.splitter_8.setOrientation(Qt.Vertical)
        self.splitter_4 = QSplitter(self.splitter_8)
        self.splitter_4.setObjectName(u"splitter_4")
        self.splitter_4.setOrientation(Qt.Vertical)
        self.splitter_5 = QSplitter(self.splitter_4)
        self.splitter_5.setObjectName(u"splitter_5")
        self.splitter_5.setOrientation(Qt.Vertical)
        self.label = QLabel(self.splitter_5)
        self.label.setObjectName(u"label")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy1)
        self.label.setMinimumSize(QSize(2, 2))
        self.label.setMaximumSize(QSize(512, 512))
        font2 = QFont()
        font2.setPointSize(9)
        font2.setBold(True)
        font2.setItalic(False)
        font2.setUnderline(True)
        font2.setKerning(True)
        self.label.setFont(font2)
        self.label.setStyleSheet(u"color: rgb(255, 170, 0);\n"
"color: rgb(255, 85, 0);")
        self.splitter_5.addWidget(self.label)
        self.layoutWidget1 = QWidget(self.splitter_5)
        self.layoutWidget1.setObjectName(u"layoutWidget1")
        self.gridLayout = QGridLayout(self.layoutWidget1)
#ifndef Q_OS_MAC
        self.gridLayout.setSpacing(-1)
#endif
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.textbox_offset_2 = QLineEdit(self.layoutWidget1)
        self.textbox_offset_2.setObjectName(u"textbox_offset_2")
        font3 = QFont()
        font3.setPointSize(9)
        font3.setBold(False)
        font3.setKerning(False)
        self.textbox_offset_2.setFont(font3)

        self.gridLayout.addWidget(self.textbox_offset_2, 6, 1, 1, 1)

        self.textbox_offset_1 = QLineEdit(self.layoutWidget1)
        self.textbox_offset_1.setObjectName(u"textbox_offset_1")
        self.textbox_offset_1.setFont(font3)

        self.gridLayout.addWidget(self.textbox_offset_1, 6, 0, 1, 1)

        self.button_offsets = QPushButton(self.layoutWidget1)
        self.button_offsets.setObjectName(u"button_offsets")
        font4 = QFont()
        font4.setPointSize(8)
        font4.setBold(True)
        self.button_offsets.setFont(font4)
        self.button_offsets.setStyleSheet(u"background-color: rgb(75, 168, 255);")

        self.gridLayout.addWidget(self.button_offsets, 7, 0, 1, 2)

        self.label_offset_1 = QLabel(self.layoutWidget1)
        self.label_offset_1.setObjectName(u"label_offset_1")
        font5 = QFont()
        font5.setFamilies([u"Arial"])
        font5.setPointSize(11)
        font5.setBold(True)
        font5.setItalic(False)
        self.label_offset_1.setFont(font5)

        self.gridLayout.addWidget(self.label_offset_1, 3, 0, 3, 1)

        self.label_offset_2 = QLabel(self.layoutWidget1)
        self.label_offset_2.setObjectName(u"label_offset_2")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.label_offset_2.sizePolicy().hasHeightForWidth())
        self.label_offset_2.setSizePolicy(sizePolicy2)
        self.label_offset_2.setFont(font5)

        self.gridLayout.addWidget(self.label_offset_2, 3, 1, 3, 1)

        self.line = QFrame(self.layoutWidget1)
        self.line.setObjectName(u"line")
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)

        self.splitter_5.addWidget(self.layoutWidget1)
        self.splitter_4.addWidget(self.splitter_5)
        self.splitter_8.addWidget(self.splitter_4)
        self.line_2 = QFrame(self.splitter_8)
        self.line_2.setObjectName(u"line_2")
        self.line_2.setFrameShape(QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QFrame.Shadow.Sunken)
        self.splitter_8.addWidget(self.line_2)
        self.label_5 = QLabel(self.splitter_8)
        self.label_5.setObjectName(u"label_5")
        sizePolicy1.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy1)
        self.label_5.setMinimumSize(QSize(2, 2))
        self.label_5.setMaximumSize(QSize(512, 512))
        self.label_5.setFont(font2)
        self.label_5.setStyleSheet(u"color: rgb(255, 170, 0);\n"
"color: rgb(255, 85, 0);")
        self.splitter_8.addWidget(self.label_5)
        self.splitter_7.addWidget(self.splitter_8)
        self.splitter_6.addWidget(self.splitter_7)

        self.gridLayout_6.addWidget(self.splitter_6, 0, 0, 1, 1)

        self.gridLayout_7 = QGridLayout()
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.label_amplitude_2 = QLabel(self.layoutWidget)
        self.label_amplitude_2.setObjectName(u"label_amplitude_2")
        sizePolicy3 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Maximum)
        sizePolicy3.setHorizontalStretch(0)
        sizePolicy3.setVerticalStretch(0)
        sizePolicy3.setHeightForWidth(self.label_amplitude_2.sizePolicy().hasHeightForWidth())
        self.label_amplitude_2.setSizePolicy(sizePolicy3)
        font6 = QFont()
        font6.setFamilies([u"Arial"])
        font6.setPointSize(9)
        font6.setBold(True)
        font6.setItalic(False)
        self.label_amplitude_2.setFont(font6)

        self.gridLayout_7.addWidget(self.label_amplitude_2, 0, 1, 1, 1)

        self.textbox_direction_end_y = QLineEdit(self.layoutWidget)
        self.textbox_direction_end_y.setObjectName(u"textbox_direction_end_y")
        self.textbox_direction_end_y.setFont(font3)

        self.gridLayout_7.addWidget(self.textbox_direction_end_y, 2, 1, 1, 1)

        self.textbox_direction_start_x = QLineEdit(self.layoutWidget)
        self.textbox_direction_start_x.setObjectName(u"textbox_direction_start_x")
        self.textbox_direction_start_x.setFont(font3)

        self.gridLayout_7.addWidget(self.textbox_direction_start_x, 1, 0, 1, 1)

        self.textbox_direction_end_x = QLineEdit(self.layoutWidget)
        self.textbox_direction_end_x.setObjectName(u"textbox_direction_end_x")
        self.textbox_direction_end_x.setFont(font3)

        self.gridLayout_7.addWidget(self.textbox_direction_end_x, 1, 1, 1, 1)

        self.textbox_direction_start_y = QLineEdit(self.layoutWidget)
        self.textbox_direction_start_y.setObjectName(u"textbox_direction_start_y")
        self.textbox_direction_start_y.setFont(font3)

        self.gridLayout_7.addWidget(self.textbox_direction_start_y, 2, 0, 1, 1)

        self.label_frequency = QLabel(self.layoutWidget)
        self.label_frequency.setObjectName(u"label_frequency")
        sizePolicy4 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Maximum)
        sizePolicy4.setHorizontalStretch(0)
        sizePolicy4.setVerticalStretch(0)
        sizePolicy4.setHeightForWidth(self.label_frequency.sizePolicy().hasHeightForWidth())
        self.label_frequency.setSizePolicy(sizePolicy4)
        font7 = QFont()
        font7.setFamilies([u"Arial"])
        font7.setPointSize(10)
        font7.setBold(True)
        font7.setItalic(False)
        self.label_frequency.setFont(font7)

        self.gridLayout_7.addWidget(self.label_frequency, 0, 0, 1, 1)

        self.button_send_start_vec = QPushButton(self.layoutWidget)
        self.button_send_start_vec.setObjectName(u"button_send_start_vec")
        self.button_send_start_vec.setFont(font7)
        self.button_send_start_vec.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button_send_start_vec.setStyleSheet(u"background-color: rgb(108, 160, 255);")

        self.gridLayout_7.addWidget(self.button_send_start_vec, 3, 0, 1, 2)

        self.line_7 = QFrame(self.layoutWidget)
        self.line_7.setObjectName(u"line_7")
        self.line_7.setFrameShape(QFrame.Shape.HLine)
        self.line_7.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_7.addWidget(self.line_7, 4, 0, 1, 2)


        self.gridLayout_6.addLayout(self.gridLayout_7, 1, 0, 1, 1)

        self.splitter_9 = QSplitter(self.layoutWidget)
        self.splitter_9.setObjectName(u"splitter_9")
        self.splitter_9.setOrientation(Qt.Vertical)
        self.splitter_10 = QSplitter(self.splitter_9)
        self.splitter_10.setObjectName(u"splitter_10")
        self.splitter_10.setOrientation(Qt.Vertical)
        self.splitter_11 = QSplitter(self.splitter_10)
        self.splitter_11.setObjectName(u"splitter_11")
        self.splitter_11.setOrientation(Qt.Vertical)
        self.splitter_12 = QSplitter(self.splitter_11)
        self.splitter_12.setObjectName(u"splitter_12")
        self.splitter_12.setOrientation(Qt.Vertical)
        self.line_8 = QFrame(self.splitter_12)
        self.line_8.setObjectName(u"line_8")
        self.line_8.setFrameShape(QFrame.Shape.HLine)
        self.line_8.setFrameShadow(QFrame.Shadow.Sunken)
        self.splitter_12.addWidget(self.line_8)
        self.label_3 = QLabel(self.splitter_12)
        self.label_3.setObjectName(u"label_3")
        sizePolicy5 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy5.setHorizontalStretch(0)
        sizePolicy5.setVerticalStretch(0)
        sizePolicy5.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy5)
        self.label_3.setMinimumSize(QSize(2, 2))
        self.label_3.setMaximumSize(QSize(512, 512))
        font8 = QFont()
        font8.setPointSize(12)
        font8.setBold(True)
        font8.setKerning(True)
        self.label_3.setFont(font8)
        self.splitter_12.addWidget(self.label_3)
        self.textbox_standard_sampling_rate = QLineEdit(self.splitter_12)
        self.textbox_standard_sampling_rate.setObjectName(u"textbox_standard_sampling_rate")
        self.textbox_standard_sampling_rate.setFont(font3)
        self.splitter_12.addWidget(self.textbox_standard_sampling_rate)
        self.layoutWidget2 = QWidget(self.splitter_12)
        self.layoutWidget2.setObjectName(u"layoutWidget2")
        self.gridLayout_4 = QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setObjectName(u"gridLayout_4")
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.line_3 = QFrame(self.layoutWidget2)
        self.line_3.setObjectName(u"line_3")
        self.line_3.setFrameShape(QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_4.addWidget(self.line_3, 0, 0, 1, 1)

        self.label_direction_4 = QLabel(self.layoutWidget2)
        self.label_direction_4.setObjectName(u"label_direction_4")
        sizePolicy6 = QSizePolicy(QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)
        sizePolicy6.setHorizontalStretch(3)
        sizePolicy6.setVerticalStretch(2)
        sizePolicy6.setHeightForWidth(self.label_direction_4.sizePolicy().hasHeightForWidth())
        self.label_direction_4.setSizePolicy(sizePolicy6)
        font9 = QFont()
        font9.setFamilies([u"Linux Libertine"])
        font9.setPointSize(12)
        font9.setBold(True)
        self.label_direction_4.setFont(font9)
        self.label_direction_4.setLayoutDirection(Qt.LeftToRight)
        self.label_direction_4.setFrameShape(QFrame.NoFrame)
        self.label_direction_4.setFrameShadow(QFrame.Plain)
        self.label_direction_4.setLineWidth(0)

        self.gridLayout_4.addWidget(self.label_direction_4, 1, 0, 1, 1)

        self.line_4 = QFrame(self.layoutWidget2)
        self.line_4.setObjectName(u"line_4")
        self.line_4.setFrameShape(QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_4.addWidget(self.line_4, 2, 0, 1, 1)

        self.splitter = QSplitter(self.layoutWidget2)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Horizontal)
        self.textbox_vector_start_time = QLineEdit(self.splitter)
        self.textbox_vector_start_time.setObjectName(u"textbox_vector_start_time")
        self.textbox_vector_start_time.setFont(font3)
        self.splitter.addWidget(self.textbox_vector_start_time)
        self.textbox_vector_end_time = QLineEdit(self.splitter)
        self.textbox_vector_end_time.setObjectName(u"textbox_vector_end_time")
        self.textbox_vector_end_time.setFont(font3)
        self.splitter.addWidget(self.textbox_vector_end_time)

        self.gridLayout_4.addWidget(self.splitter, 3, 0, 1, 1)

        self.splitter_2 = QSplitter(self.layoutWidget2)
        self.splitter_2.setObjectName(u"splitter_2")
        self.splitter_2.setOrientation(Qt.Horizontal)
        self.label_2 = QLabel(self.splitter_2)
        self.label_2.setObjectName(u"label_2")
        sizePolicy5.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy5)
        self.label_2.setMinimumSize(QSize(2, 2))
        self.label_2.setMaximumSize(QSize(512, 512))
        font10 = QFont()
        font10.setPointSize(11)
        font10.setBold(True)
        font10.setKerning(True)
        self.label_2.setFont(font10)
        self.splitter_2.addWidget(self.label_2)
        self.label_4 = QLabel(self.splitter_2)
        self.label_4.setObjectName(u"label_4")
        font11 = QFont()
        font11.setPointSize(11)
        font11.setBold(True)
        self.label_4.setFont(font11)
        self.splitter_2.addWidget(self.label_4)

        self.gridLayout_4.addWidget(self.splitter_2, 4, 0, 1, 1)

        self.splitter_12.addWidget(self.layoutWidget2)
        self.splitter_3 = QSplitter(self.splitter_12)
        self.splitter_3.setObjectName(u"splitter_3")
        self.splitter_3.setOrientation(Qt.Horizontal)
        self.textbox_input_sampling_rate = QLineEdit(self.splitter_3)
        self.textbox_input_sampling_rate.setObjectName(u"textbox_input_sampling_rate")
        self.textbox_input_sampling_rate.setFont(font3)
        self.splitter_3.addWidget(self.textbox_input_sampling_rate)
        self.textbox_input_sampling_time = QLineEdit(self.splitter_3)
        self.textbox_input_sampling_time.setObjectName(u"textbox_input_sampling_time")
        self.textbox_input_sampling_time.setFont(font3)
        self.splitter_3.addWidget(self.textbox_input_sampling_time)
        self.splitter_12.addWidget(self.splitter_3)
        self.splitter_11.addWidget(self.splitter_12)
        self.splitter_10.addWidget(self.splitter_11)
        self.splitter_9.addWidget(self.splitter_10)

        self.gridLayout_6.addWidget(self.splitter_9, 2, 0, 1, 1)

        self.verticalLayout = QVBoxLayout()
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.button_start_acquistion = QPushButton(self.layoutWidget)
        self.button_start_acquistion.setObjectName(u"button_start_acquistion")
        font12 = QFont()
        font12.setFamilies([u"Arial"])
        font12.setPointSize(12)
        font12.setBold(True)
        font12.setItalic(False)
        self.button_start_acquistion.setFont(font12)
        self.button_start_acquistion.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button_start_acquistion.setStyleSheet(u"background-color: rgb(57, 255, 100);")

        self.verticalLayout.addWidget(self.button_start_acquistion)

        self.line_6 = QFrame(self.layoutWidget)
        self.line_6.setObjectName(u"line_6")
        self.line_6.setFrameShape(QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout.addWidget(self.line_6)

        self.save_button = QPushButton(self.layoutWidget)
        self.save_button.setObjectName(u"save_button")
        font13 = QFont()
        font13.setFamilies([u"Arial"])
        font13.setPointSize(12)
        font13.setItalic(False)
        self.save_button.setFont(font13)
        self.save_button.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))

        self.verticalLayout.addWidget(self.save_button)


        self.gridLayout_6.addLayout(self.verticalLayout, 3, 0, 1, 1)

        self.line_5 = QFrame(self.layoutWidget)
        self.line_5.setObjectName(u"line_5")
        self.line_5.setFrameShape(QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QFrame.Shadow.Sunken)

        self.gridLayout_6.addWidget(self.line_5, 4, 0, 1, 1)

        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.gridLayout_3 = QGridLayout()
#ifndef Q_OS_MAC
        self.gridLayout_3.setSpacing(-1)
#endif
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.timeInterval_comboBox = QComboBox(self.layoutWidget)
        self.timeInterval_comboBox.addItem("")
        self.timeInterval_comboBox.addItem("")
        self.timeInterval_comboBox.addItem("")
        self.timeInterval_comboBox.setObjectName(u"timeInterval_comboBox")
        font14 = QFont()
        font14.setPointSize(10)
        font14.setBold(False)
        self.timeInterval_comboBox.setFont(font14)

        self.gridLayout_3.addWidget(self.timeInterval_comboBox, 3, 1, 1, 1)

        self.graph_stop_button = QPushButton(self.layoutWidget)
        self.graph_stop_button.setObjectName(u"graph_stop_button")
        self.graph_stop_button.setFont(font)
        self.graph_stop_button.setStyleSheet(u"color: rgb(255, 85, 0);\n"
"background-color: rgb(255, 170, 0);")

        self.gridLayout_3.addWidget(self.graph_stop_button, 2, 0, 1, 1)

        self.normalise_button = QPushButton(self.layoutWidget)
        self.normalise_button.setObjectName(u"normalise_button")
        font15 = QFont()
        font15.setPointSize(12)
        self.normalise_button.setFont(font15)
        self.normalise_button.setStyleSheet(u"background-color: rgb(81, 0, 255);")

        self.gridLayout_3.addWidget(self.normalise_button, 4, 0, 1, 2)

        self.button_auto_range = QPushButton(self.layoutWidget)
        self.button_auto_range.setObjectName(u"button_auto_range")
        self.button_auto_range.setFont(font)
        self.button_auto_range.setStyleSheet(u"color: rgb(255, 85, 0);\n"
"background-color: rgb(255, 170, 0);")

        self.gridLayout_3.addWidget(self.button_auto_range, 2, 1, 1, 1)

        self.label_time_2 = QLabel(self.layoutWidget)
        self.label_time_2.setObjectName(u"label_time_2")
        font16 = QFont()
        font16.setFamilies([u"Linux Libertine"])
        font16.setPointSize(11)
        font16.setBold(True)
        self.label_time_2.setFont(font16)

        self.gridLayout_3.addWidget(self.label_time_2, 3, 0, 1, 1)

        self.label_frequency_2 = QLabel(self.layoutWidget)
        self.label_frequency_2.setObjectName(u"label_frequency_2")
        sizePolicy4.setHeightForWidth(self.label_frequency_2.sizePolicy().hasHeightForWidth())
        self.label_frequency_2.setSizePolicy(sizePolicy4)
        font17 = QFont()
        font17.setFamilies([u"Arial"])
        font17.setPointSize(12)
        font17.setBold(True)
        font17.setItalic(False)
        font17.setKerning(False)
        self.label_frequency_2.setFont(font17)
        self.label_frequency_2.setLineWidth(0)
        self.label_frequency_2.setIndent(0)

        self.gridLayout_3.addWidget(self.label_frequency_2, 0, 0, 1, 1)

        self.lcdNumber = QLCDNumber(self.layoutWidget)
        self.lcdNumber.setObjectName(u"lcdNumber")
        font18 = QFont()
        font18.setPointSize(9)
        self.lcdNumber.setFont(font18)
        self.lcdNumber.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(30, 229, 0);\n"
"border-color: rgb(255, 255, 127);")

        self.gridLayout_3.addWidget(self.lcdNumber, 1, 0, 1, 1)

        self.lcdNumber_vector = QLCDNumber(self.layoutWidget)
        self.lcdNumber_vector.setObjectName(u"lcdNumber_vector")
        font19 = QFont()
        font19.setPointSize(10)
        self.lcdNumber_vector.setFont(font19)
        self.lcdNumber_vector.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"color: rgb(30, 229, 0);\n"
"border-color: rgb(255, 255, 127);")

        self.gridLayout_3.addWidget(self.lcdNumber_vector, 1, 1, 1, 1)

        self.label_frequency_3 = QLabel(self.layoutWidget)
        self.label_frequency_3.setObjectName(u"label_frequency_3")
        sizePolicy4.setHeightForWidth(self.label_frequency_3.sizePolicy().hasHeightForWidth())
        self.label_frequency_3.setSizePolicy(sizePolicy4)
        self.label_frequency_3.setFont(font12)

        self.gridLayout_3.addWidget(self.label_frequency_3, 0, 1, 1, 1)

        self.button_rotate = QPushButton(self.layoutWidget)
        self.button_rotate.setObjectName(u"button_rotate")
        self.button_rotate.setFont(font12)
        self.button_rotate.setCursor(QCursor(Qt.CursorShape.PointingHandCursor))
        self.button_rotate.setStyleSheet(u"background-color: rgb(57, 255, 100);")

        self.gridLayout_3.addWidget(self.button_rotate, 5, 0, 1, 2)


        self.gridLayout_2.addLayout(self.gridLayout_3, 3, 0, 1, 1)

        self.status_label = QLabel(self.layoutWidget)
        self.status_label.setObjectName(u"status_label")
        font20 = QFont()
        font20.setFamilies([u"Arial"])
        font20.setPointSize(16)
        font20.setBold(True)
        font20.setItalic(False)
        self.status_label.setFont(font20)
        self.status_label.setStyleSheet(u"color: rgb(85, 170, 0);")

        self.gridLayout_2.addWidget(self.status_label, 0, 0, 1, 1)

        self.gridLayout_2.setRowStretch(0, 4)

        self.gridLayout_6.addLayout(self.gridLayout_2, 5, 0, 1, 1)

        self.splitter_13.addWidget(self.layoutWidget)

        self.gridLayout_8.addWidget(self.splitter_13, 0, 0, 1, 1)

        self.gridLayout_5 = QGridLayout()
        self.gridLayout_5.setObjectName(u"gridLayout_5")
        self.select_mode_comboBox = QComboBox(self.centralwidget)
        self.select_mode_comboBox.addItem("")
        self.select_mode_comboBox.addItem("")
        self.select_mode_comboBox.addItem("")
        self.select_mode_comboBox.setObjectName(u"select_mode_comboBox")
        font21 = QFont()
        font21.setFamilies([u"Arial"])
        font21.setPointSize(13)
        font21.setBold(True)
        font21.setItalic(True)
        self.select_mode_comboBox.setFont(font21)

        self.gridLayout_5.addWidget(self.select_mode_comboBox, 0, 2, 1, 1)

        self.filter_checkbox = QCheckBox(self.centralwidget)
        self.filter_checkbox.setObjectName(u"filter_checkbox")
        self.filter_checkbox.setEnabled(True)
        font22 = QFont()
        font22.setFamilies([u"Arial"])
        font22.setPointSize(12)
        font22.setBold(False)
        font22.setItalic(True)
        font22.setUnderline(False)
        font22.setStrikeOut(False)
        self.filter_checkbox.setFont(font22)
        self.filter_checkbox.setChecked(True)

        self.gridLayout_5.addWidget(self.filter_checkbox, 0, 1, 1, 1)

        self.TITLE = QLabel(self.centralwidget)
        self.TITLE.setObjectName(u"TITLE")
        font23 = QFont()
        font23.setFamilies([u"Arial"])
        font23.setPointSize(13)
        font23.setBold(True)
        font23.setItalic(False)
        font23.setUnderline(False)
        self.TITLE.setFont(font23)
        self.TITLE.setStyleSheet(u"color: rgb(0, 0, 127);")
        self.TITLE.setTextFormat(Qt.PlainText)

        self.gridLayout_5.addWidget(self.TITLE, 0, 0, 1, 1)

        self.k_b_label = QLabel(self.centralwidget)
        self.k_b_label.setObjectName(u"k_b_label")
        self.k_b_label.setFont(font3)

        self.gridLayout_5.addWidget(self.k_b_label, 3, 0, 1, 3)

        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        self.graphicsView.setObjectName(u"graphicsView")
        font24 = QFont()
        font24.setFamilies([u"Arial"])
        font24.setItalic(False)
        self.graphicsView.setFont(font24)
        self.graphicsView.setStyleSheet(u"background-color: rgb(0, 0, 0);")

        self.gridLayout_5.addWidget(self.graphicsView, 2, 0, 1, 3)


        self.gridLayout_8.addLayout(self.gridLayout_5, 0, 1, 1, 1)

        self.gridLayout_8.setColumnStretch(0, 1)
        self.gridLayout_8.setColumnStretch(1, 7)
        CreepTestGUI.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(CreepTestGUI)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1337, 37))
        self.menubar.setFont(font3)
        self.menuRestart = QMenu(self.menubar)
        self.menuRestart.setObjectName(u"menuRestart")
        font25 = QFont()
        font25.setKerning(False)
        self.menuRestart.setFont(font25)
        CreepTestGUI.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(CreepTestGUI)
        self.statusbar.setObjectName(u"statusbar")
        CreepTestGUI.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuRestart.menuAction())
        self.menuRestart.addAction(self.actionHardware_reset)
        self.menuRestart.addAction(self.actionSoftware_restart)

        self.retranslateUi(CreepTestGUI)

        QMetaObject.connectSlotsByName(CreepTestGUI)
    # setupUi

    def retranslateUi(self, CreepTestGUI):
        CreepTestGUI.setWindowTitle(QCoreApplication.translate("CreepTestGUI", u"MainWindow", None))
#if QT_CONFIG(tooltip)
        CreepTestGUI.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.actionHardware_reset.setText(QCoreApplication.translate("CreepTestGUI", u"Hardware reset", None))
        self.actionSoftware_restart.setText(QCoreApplication.translate("CreepTestGUI", u"Software restart", None))
        self.label.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body style = \"line-height: 0.3;\"><p align=\"center\">Ambient field compensation</p><p align=\"center\">in <span style=\" font-weight:600;\">mA</body></html>", None))
#if QT_CONFIG(tooltip)
        self.textbox_offset_2.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.textbox_offset_1.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.button_offsets.setText(QCoreApplication.translate("CreepTestGUI", u"Send offsets", None))
        self.label_offset_1.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body><p align=\"center\">Offset 1 </p></body></html>", None))
        self.label_offset_2.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body><p align=\"center\">Offset 2</p></body></html>", None))
        self.label_5.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body style = \"line-height: 0.3;\"><p align=\"center\">Setting up vector</p><p align=\"center\">in <span style=\" font-weight:600;\">mA</body></html>", None))
        self.label_amplitude_2.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body><p align=\"center\">End vector</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.textbox_direction_end_y.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.textbox_direction_start_x.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.textbox_direction_start_x.setText("")
#if QT_CONFIG(tooltip)
        self.textbox_direction_end_x.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.textbox_direction_start_y.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_frequency.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body><p align=\"center\">Start vector</p></body></html>", None))
        self.button_send_start_vec.setText(QCoreApplication.translate("CreepTestGUI", u"Send start vector", None))
        self.label_3.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">Standard sampling frequency / Hz</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.textbox_standard_sampling_rate.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_direction_4.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body><p align=\"center\"><span style=\" font-size:11pt;\">Respective vector duration / s</span></p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.textbox_vector_start_time.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.textbox_vector_end_time.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.label_2.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body><p align=\"center\">Desired SR</p></body></html>", None))
        self.label_4.setText(QCoreApplication.translate("CreepTestGUI", u" for time /s", None))
#if QT_CONFIG(tooltip)
        self.textbox_input_sampling_rate.setToolTip("")
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.textbox_input_sampling_time.setToolTip("")
#endif // QT_CONFIG(tooltip)
        self.button_start_acquistion.setText(QCoreApplication.translate("CreepTestGUI", u"Start acquisition", None))
        self.save_button.setText("")
        self.timeInterval_comboBox.setItemText(0, QCoreApplication.translate("CreepTestGUI", u"500ms", None))
        self.timeInterval_comboBox.setItemText(1, QCoreApplication.translate("CreepTestGUI", u"100ms", None))
        self.timeInterval_comboBox.setItemText(2, QCoreApplication.translate("CreepTestGUI", u"1000ms", None))

        self.graph_stop_button.setText(QCoreApplication.translate("CreepTestGUI", u"Pause live-graph", None))
        self.normalise_button.setText(QCoreApplication.translate("CreepTestGUI", u"Normalise Voltage", None))
        self.button_auto_range.setText(QCoreApplication.translate("CreepTestGUI", u"Auto-range", None))
        self.label_time_2.setText(QCoreApplication.translate("CreepTestGUI", u"Time Interval (s)", None))
        self.label_frequency_2.setText(QCoreApplication.translate("CreepTestGUI", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'Arial'; font-size:10pt; font-weight:600; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Total time left</p></body></html>", None))
        self.label_frequency_3.setText(QCoreApplication.translate("CreepTestGUI", u"<html><head/><body><p align=\"center\">Vector </p></body></html>", None))
        self.button_rotate.setText(QCoreApplication.translate("CreepTestGUI", u"Rotate magnet for first 10 rotation", None))
        self.status_label.setText(QCoreApplication.translate("CreepTestGUI", u"Status : Ready.......................", None))
        self.select_mode_comboBox.setItemText(0, QCoreApplication.translate("CreepTestGUI", u"View sensors", None))
        self.select_mode_comboBox.setItemText(1, QCoreApplication.translate("CreepTestGUI", u"View angle", None))
        self.select_mode_comboBox.setItemText(2, QCoreApplication.translate("CreepTestGUI", u"View phase difference", None))

        self.filter_checkbox.setText(QCoreApplication.translate("CreepTestGUI", u"Use live FIR filter", None))
        self.TITLE.setText(QCoreApplication.translate("CreepTestGUI", u"Creep Test Window", None))
        self.k_b_label.setText(QCoreApplication.translate("CreepTestGUI", u"k_b_1  =                     k_b_2=                                          ", None))
        self.menuRestart.setTitle(QCoreApplication.translate("CreepTestGUI", u"Restart", None))
    # retranslateUi

