
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/opt/homebrew/share/cmake/Modules/CMakeDetermineSystem.cmake:200 (message)"
      - "CMakeLists.txt:21 (project)"
    message: |
      The target system is: Generic -  - arm
      The host system is: Darwin - 24.4.0 - arm64
...
