# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'button_tekan_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_data_capture_Window(object):
    def setupUi(self, data_capture_Window):
        data_capture_Window.setObjectName("data_capture_Window")
        data_capture_Window.resize(1350, 891)
        self.centralwidget = QtWidgets.QWidget(data_capture_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 20, 1311, 731))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.stop_button = QtWidgets.QPushButton(self.centralwidget)
        self.stop_button.setGeometry(QtCore.QRect(20, 770, 151, 71))
        self.stop_button.setStyleSheet("background-color: rgb(255, 0, 0);\n"
"border-top-color: rgb(0, 0, 0);\n"
"border-color: rgb(0, 0, 0);")
        self.stop_button.setObjectName("stop_button")
        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        self.save_button.setGeometry(QtCore.QRect(200, 770, 91, 71))
        self.save_button.setText("")
        self.save_button.setObjectName("save_button")
        data_capture_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(data_capture_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1350, 21))
        self.menubar.setObjectName("menubar")
        data_capture_Window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(data_capture_Window)
        self.statusbar.setObjectName("statusbar")
        data_capture_Window.setStatusBar(self.statusbar)

        self.retranslateUi(data_capture_Window)
        QtCore.QMetaObject.connectSlotsByName(data_capture_Window)

    def retranslateUi(self, data_capture_Window):
        _translate = QtCore.QCoreApplication.translate
        data_capture_Window.setWindowTitle(_translate("data_capture_Window", "MainWindow"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("data_capture_Window", "Time (s)"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("data_capture_Window", "Voltage 1 (V)"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("data_capture_Window", "Voltage 2 (V)"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("data_capture_Window", "Current 1 (mA)"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("data_capture_Window", "Current 2 (mA)"))
        self.stop_button.setText(_translate("data_capture_Window", "Stop"))
