# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 529)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_experiment_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.choose_experiment_comboBox.setGeometry(QtCore.QRect(310, 100, 201, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.choose_experiment_comboBox.setFont(font)
        self.choose_experiment_comboBox.setObjectName("choose_experiment_comboBox")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        self.choose_electronic_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.choose_electronic_comboBox.setGeometry(QtCore.QRect(50, 100, 201, 31))
        self.choose_electronic_comboBox.setObjectName("choose_electronic_comboBox")
        self.choose_electronic_comboBox.addItem("")
        self.choose_electronic_comboBox.addItem("")
        self.choose_electronic_comboBox.addItem("")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(50, 60, 501, 31))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.label_choose_electronic = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("CMU Serif")
        font.setPointSize(12)
        self.label_choose_electronic.setFont(font)
        self.label_choose_electronic.setObjectName("label_choose_electronic")
        self.label_choose_experiment = QtWidgets.QLabel(self.splitter)
        font = QtGui.QFont()
        font.setFamily("CMU Serif")
        font.setPointSize(12)
        self.label_choose_experiment.setFont(font)
        self.label_choose_experiment.setObjectName("label_choose_experiment")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.choose_experiment_comboBox.setItemText(0, _translate("MainWindow", "Choose experiment"))
        self.choose_experiment_comboBox.setItemText(1, _translate("MainWindow", "Control shear rate"))
        self.choose_experiment_comboBox.setItemText(2, _translate("MainWindow", "Creep experiment"))
        self.choose_experiment_comboBox.setItemText(3, _translate("MainWindow", "Steady shear stress"))
        self.choose_experiment_comboBox.setItemText(4, _translate("MainWindow", "Dynamic"))
        self.choose_electronic_comboBox.setItemText(0, _translate("MainWindow", "Choose now"))
        self.choose_electronic_comboBox.setItemText(1, _translate("MainWindow", "Electronic 1"))
        self.choose_electronic_comboBox.setItemText(2, _translate("MainWindow", "Electronic 2"))
        self.label_choose_electronic.setText(_translate("MainWindow", "Types of experiment "))
        self.label_choose_experiment.setText(_translate("MainWindow", "Types of experiment "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
