# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(501, 319)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.photo_label = QtWidgets.QLabel(self.centralwidget)
        self.photo_label.setGeometry(QtCore.QRect(20, 20, 181, 51))
        self.photo_label.setText("")
        self.photo_label.setScaledContents(False)
        self.photo_label.setObjectName("photo_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(80, 100, 352, 76))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_choose_experiment = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_choose_experiment.setFont(font)
        self.label_choose_experiment.setObjectName("label_choose_experiment")
        self.gridLayout.addWidget(self.label_choose_experiment, 0, 2, 1, 1)
        self.choose_electronic_comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.choose_electronic_comboBox.setFont(font)
        self.choose_electronic_comboBox.setObjectName("choose_electronic_comboBox")
        self.choose_electronic_comboBox.addItem("")
        self.choose_electronic_comboBox.addItem("")
        self.choose_electronic_comboBox.addItem("")
        self.gridLayout.addWidget(self.choose_electronic_comboBox, 1, 0, 1, 2)
        self.label_choose_electronic = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_choose_electronic.setFont(font)
        self.label_choose_electronic.setObjectName("label_choose_electronic")
        self.gridLayout.addWidget(self.label_choose_electronic, 0, 0, 1, 2)
        self.choose_experiment_comboBox = QtWidgets.QComboBox(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.choose_experiment_comboBox.setFont(font)
        self.choose_experiment_comboBox.setObjectName("choose_experiment_comboBox")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        self.gridLayout.addWidget(self.choose_experiment_comboBox, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 501, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_choose_experiment.setText(_translate("MainWindow", "Types of experiment "))
        self.choose_electronic_comboBox.setItemText(0, _translate("MainWindow", "Choose now"))
        self.choose_electronic_comboBox.setItemText(1, _translate("MainWindow", "Electronic 1"))
        self.choose_electronic_comboBox.setItemText(2, _translate("MainWindow", "Electronic 2"))
        self.label_choose_electronic.setText(_translate("MainWindow", "Choose Electronics"))
        self.choose_experiment_comboBox.setItemText(0, _translate("MainWindow", "Choose experiment"))
        self.choose_experiment_comboBox.setItemText(1, _translate("MainWindow", "Control shear rate"))
        self.choose_experiment_comboBox.setItemText(2, _translate("MainWindow", "Pid-Controller (dev)"))
