# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_test.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(611, 529)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 60, 191, 31))
        font = QtGui.QFont()
        font.setFamily("CMU Serif")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.choose_experiment_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.choose_experiment_comboBox.setGeometry(QtCore.QRect(20, 100, 171, 22))
        self.choose_experiment_comboBox.setObjectName("choose_experiment_comboBox")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        self.choose_experiment_comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Types of experiment "))
        self.choose_experiment_comboBox.setItemText(0, _translate("MainWindow", "Control shear rate"))
        self.choose_experiment_comboBox.setItemText(1, _translate("MainWindow", "Creep experiment"))
        self.choose_experiment_comboBox.setItemText(2, _translate("MainWindow", "Steady shear stress"))
        self.choose_experiment_comboBox.setItemText(3, _translate("MainWindow", "Dynamic"))
