# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mapheus_main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from pyqtgraph import GraphicsLayoutWidget


class Ui_Title(object):
    def setupUi(self, Title):
        Title.setObjectName("Title")
        Title.resize(1280, 1172)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(13)
        sizePolicy.setHeightForWidth(Title.sizePolicy().hasHeightForWidth())
        Title.setSizePolicy(sizePolicy)
        Title.setMouseTracking(False)
        Title.setToolTip("")
        Title.setLayoutDirection(QtCore.Qt.LeftToRight)
        Title.setAutoFillBackground(False)
        Title.setInputMethodHints(QtCore.Qt.ImhNone)

        self.centralwidget = QtWidgets.QWidget(Title)
        self.centralwidget.setObjectName("centralwidget")

        root = QtWidgets.QHBoxLayout(self.centralwidget)
        root.setContentsMargins(10, 10, 10, 10)
        root.setSpacing(12)

        # ── LEFT PANEL ────────────────────────────────────────────────
        left = QtWidgets.QVBoxLayout()
        left.setSpacing(8)

        # ── GroupBox: Experiment control ────────────────────────────
        self.group_experiment = QtWidgets.QGroupBox("Experiment", self.centralwidget)
        self.group_experiment.setObjectName("group_experiment")
        exp = QtWidgets.QVBoxLayout(self.group_experiment)
        exp.setSpacing(4)
        exp.setContentsMargins(8, 14, 8, 8)

        self.button_start_experiment = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_start_experiment.setFont(font)
        self.button_start_experiment.setStyleSheet(
            "color: rgb(255, 255, 255);\nbackground-color: rgb(45, 3, 255);"
        )
        self.button_start_experiment.setObjectName("button_start_experiment")
        exp.addWidget(self.button_start_experiment)

        self.button_start_kb = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_start_kb.setFont(font)
        self.button_start_kb.setStyleSheet(
            "background-color: rgb(45, 3, 255);\ncolor: rgb(255, 255, 255);"
        )
        self.button_start_kb.setObjectName("button_start_kb")
        exp.addWidget(self.button_start_kb)

        self.button_rotate = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_rotate.setFont(font)
        self.button_rotate.setStyleSheet(
            "background-color: rgb(45, 3, 255);\ncolor: rgb(255, 255, 255);"
        )
        self.button_rotate.setObjectName("button_rotate")
        exp.addWidget(self.button_rotate)

        left.addWidget(self.group_experiment)

        left.addStretch(1)

        # ── Acquisition buttons ──────────────────────────────────────
        self.button_send = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_send.setFont(font)
        self.button_send.setStyleSheet(
            "background-color: rgb(67, 107, 255);\ncolor: rgb(0, 0, 0);"
        )
        self.button_send.setObjectName("button_send")
        left.addWidget(self.button_send)

        self.button_start = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.button_start.setFont(font)
        self.button_start.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_start.setStyleSheet(
            "background-color: rgb(0, 255, 0);\ncolor: rgb(0, 0, 0);"
        )
        self.button_start.setObjectName("button_start")
        left.addWidget(self.button_start)

        self.save_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setItalic(False)
        self.save_button.setFont(font)
        self.save_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.save_button.setText("")
        self.save_button.setObjectName("save_button")
        left.addWidget(self.save_button)

        # ── Status / LCD / interval row ──────────────────────────────
        status_grid = QtWidgets.QGridLayout()
        status_grid.setSpacing(6)

        self.status_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.status_label.setFont(font)
        self.status_label.setObjectName("status_label")
        status_grid.addWidget(self.status_label, 0, 0, 1, 3)

        self.lcdNumber = QtWidgets.QLCDNumber(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setStyleSheet(
            "background-color: rgb(0, 0, 0);\n"
            "color: rgb(30, 229, 0);\n"
            "border-color: rgb(255, 255, 127);"
        )
        self.lcdNumber.setObjectName("lcdNumber")
        status_grid.addWidget(self.lcdNumber, 1, 0, 2, 2)

        self.label_time_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Linux Libertine")
        font.setPointSize(11)
        self.label_time_2.setFont(font)
        self.label_time_2.setObjectName("label_time_2")
        status_grid.addWidget(self.label_time_2, 1, 2, 1, 1)

        self.timeInterval_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.timeInterval_comboBox.setFont(font)
        self.timeInterval_comboBox.setObjectName("timeInterval_comboBox")
        self.timeInterval_comboBox.addItem("")
        self.timeInterval_comboBox.addItem("")
        self.timeInterval_comboBox.addItem("")
        status_grid.addWidget(self.timeInterval_comboBox, 2, 2, 1, 1)

        left.addLayout(status_grid)

        # ── Extra buttons ─────────────────────────────────────────────
        self.graph_stop_button = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.graph_stop_button.setFont(font)
        self.graph_stop_button.setStyleSheet(
            "color: rgb(255, 255, 255);\nbackground-color: rgb(235, 157, 0);"
        )
        self.graph_stop_button.setObjectName("graph_stop_button")
        left.addWidget(self.graph_stop_button)

        root.addLayout(left, 1)

        # ── RIGHT PANEL: graph ───────────────────────────────────────
        right = QtWidgets.QVBoxLayout()
        right.setSpacing(6)

        title_row = QtWidgets.QHBoxLayout()

        self.select_mode_comboBox = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setItalic(False)
        self.select_mode_comboBox.setFont(font)
        self.select_mode_comboBox.setObjectName("select_mode_comboBox")
        self.select_mode_comboBox.addItem("")
        self.select_mode_comboBox.addItem("")
        self.select_mode_comboBox.addItem("")
        title_row.addWidget(self.select_mode_comboBox)

        title_row.addStretch()

        self.radioButton_connected = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_connected.setObjectName("radioButton_connected")
        title_row.addWidget(self.radioButton_connected)

        right.addLayout(title_row)

        self.graphicsView = GraphicsLayoutWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(False)
        self.graphicsView.setFont(font)
        self.graphicsView.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.graphicsView.setObjectName("graphicsView")
        right.addWidget(self.graphicsView, 1)

        self.k_b_label = QtWidgets.QLabel(self.centralwidget)
        self.k_b_label.setObjectName("k_b_label")
        right.addWidget(self.k_b_label)

        root.addLayout(right, 5)

        Title.setCentralWidget(self.centralwidget)

        # ── Menu / Status bar ─────────────────────────────────────────
        self.menubar = QtWidgets.QMenuBar(Title)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 21))
        self.menubar.setObjectName("menubar")
        self.menuRestart = QtWidgets.QMenu(self.menubar)
        self.menuRestart.setObjectName("menuRestart")
        self.flash_menu = QtWidgets.QMenu(self.menubar)
        self.flash_menu.setObjectName("flash_menu")
        Title.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Title)
        self.statusbar.setObjectName("statusbar")
        Title.setStatusBar(self.statusbar)
        self.actionHardware_reset = QtWidgets.QAction(Title)
        self.actionHardware_reset.setObjectName("actionHardware_reset")
        self.actionSoftware_restart = QtWidgets.QAction(Title)
        self.actionSoftware_restart.setObjectName("actionSoftware_restart")
        self.actionFlash_STM32 = QtWidgets.QAction(Title)
        self.actionFlash_STM32.setObjectName("actionFlash_STM32")
        self.menuRestart.addAction(self.actionHardware_reset)
        self.menuRestart.addAction(self.actionSoftware_restart)
        self.flash_menu.addAction(self.actionFlash_STM32)
        self.menubar.addAction(self.menuRestart.menuAction())
        self.menubar.addAction(self.flash_menu.menuAction())

        self.retranslateUi(Title)
        QtCore.QMetaObject.connectSlotsByName(Title)

    def retranslateUi(self, Title):
        _translate = QtCore.QCoreApplication.translate
        Title.setWindowTitle(_translate("Title", "MainWindow"))
        self.group_experiment.setTitle(_translate("Title", "Experiment"))
        self.k_b_label.setText(_translate("Title", "k_b_1  =                     k_b_2=                                          "))
        self.select_mode_comboBox.setItemText(0, _translate("Title", "View sensors"))
        self.select_mode_comboBox.setItemText(1, _translate("Title", "View angle"))
        self.select_mode_comboBox.setItemText(2, _translate("Title", "View phase difference"))
        self.radioButton_connected.setText(_translate("Title", "Connected"))
        self.button_start_experiment.setText(_translate("Title", "START"))
        self.button_start_kb.setText(_translate("Title", "kB Event"))
        self.button_rotate.setText(_translate("Title", "Normalise Hall-Sensors"))
        self.button_start.setText(_translate("Title", "Start acquisiton"))
        self.button_send.setText(_translate("Title", "Send data"))
        self.graph_stop_button.setText(_translate("Title", "Pause live-graph"))
        self.label_time_2.setText(_translate("Title", "Time Interval (s)"))
        self.timeInterval_comboBox.setItemText(0, _translate("Title", "500ms"))
        self.timeInterval_comboBox.setItemText(1, _translate("Title", "100ms"))
        self.timeInterval_comboBox.setItemText(2, _translate("Title", "1000ms"))
        self.status_label.setText(_translate("Title", "Status : Ready"))
        self.menuRestart.setTitle(_translate("Title", "Restart"))
        self.flash_menu.setTitle(_translate("Title", "FLASH"))
        self.actionHardware_reset.setText(_translate("Title", "Hardware reset"))
        self.actionSoftware_restart.setText(_translate("Title", "Software restart"))
        self.actionFlash_STM32.setText(_translate("Title", "Flash STM32"))
